name: Push Repository Variables

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "Target repository (format: team_name/repo_name). Leave blank to update all listed repos."
        required: false
      dry_run:
        description: "Set to 'true' to simulate without applying changes"
        required: false
        default: "false"

permissions:
  contents: read

jobs:
  sync-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.SYNC_PAT }}
        run: gh auth status

      - name: Push variables to target repositories
        env:
          GH_TOKEN: ${{ secrets.SYNC_PAT }}
          CENTRAL_REPO: ${{ github.repository }}
          INPUT_REPO: ${{ github.event.inputs.repo }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          set -euo pipefail

          echo "🔐 Using Central Repo: $CENTRAL_REPO"
          echo "🔁 Target Repo (if set): $INPUT_REPO"
          echo "🧪 Dry Run Mode: $DRY_RUN"
          echo

          # Read list of repos to update
          if [ -n "$INPUT_REPO" ]; then
            repos_list="$INPUT_REPO"
          else
            repos_list=$(grep -v '^#' repositories.txt | sed '/^\s*$/d')
          fi

          # Read list of variable names to sync
          mapfile -t VARS_TO_PUSH < repo-vars.txt

          for FULL_REPO in $repos_list; do
            echo "🔄 Processing $FULL_REPO..."

            for var in "${VARS_TO_PUSH[@]}"; do
              echo "🔍 Looking for: $var"
              value=$(gh variable get "$var" -R "$CENTRAL_REPO" -q .value 2>/dev/null || echo "")

              if [ -z "$value" ]; then
                echo "⚠️  Skipped: No variable named '$var' in central repository."
                continue
              fi

              if [ "$DRY_RUN" == "true" ]; then
                echo "🧪 [Dry-run] Would set variable '$var' in $FULL_REPO"
              else
                gh variable set "$var" -R "$FULL_REPO" -b"$value"
                echo "✅ Set variable '$var' in $FULL_REPO"
              fi
            done

            echo "✅ Done: $FULL_REPO"
            echo "--------------------------------"
          done
