name: Push Variables to Repositories

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Full repository name, e.g., raja-practise/test1-repo-new'
        required: true
        type: string

jobs:
  push-variables:
    if: |
      (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
      github.ref_name == 'main' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GHEC_BOT_TOKEN }}
      FULL_REPO: ${{ github.event.inputs.repo }}
    steps:
      - name: Setup jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate required files
        run: |
          if [ ! -s "repositories.txt" ]; then
            echo "Error: repositories.txt is missing or empty"
            exit 1
          fi
          if [ ! -s "repo-vars.txt" ]; then
            echo "Error: repo-vars.txt is missing or empty"
            exit 1
          fi

      - name: Load and filter variables
        id: build-vars
        run: |
          ORG_NAME=$(echo "$FULL_REPO" | cut -d'/' -f1)
          REPO_NAME=$(echo "$FULL_REPO" | cut -d'/' -f2)
          VAR_PREFIX=$(echo "$REPO_NAME" | tr '-' '_')_variable_

          echo "Using VAR_PREFIX: $VAR_PREFIX"

          declare -A VARS_MAP

          while read -r var_name; do
            [[ -z "$var_name" || "$var_name" == \#* ]] && continue

            if [[ "$var_name" == ${VAR_PREFIX}* ]]; then
              value=$(gh variable get "$var_name" --repo "$GITHUB_REPOSITORY" --json value -q .value || true)
              if [[ -n "$value" ]]; then
                VARS_MAP["$var_name"]="$value"
              fi
            fi
          done < repo-vars.txt

          if [ ${#VARS_MAP[@]} -eq 0 ]; then
            echo "No matching variables found for repo $FULL_REPO"
            touch vars.json
            echo "{}" > vars.json
            exit 0
          fi

          json_output="{"
          first=true
          for k in "${!VARS_MAP[@]}"; do
            [[ "$first" == true ]] && first=false || json_output+=","
            json_output+="\"$k\":\"${VARS_MAP[$k]}\""
          done
          json_output+="}"
          echo "$json_output" > vars.json
          cat vars.json

      - name: Push variables to target repos
        run: |
          if [ ! -f vars.json ] || [ "$(jq length vars.json)" -eq 0 ]; then
            echo "No variables to push. Skipping."
            exit 0
          fi

          REPO_NAME=$(echo "$FULL_REPO" | cut -d'/' -f2)

          readarray -t TARGET_REPOS < <(awk -F'/' -v t="$REPO_NAME" '$2 == t { print $0 }' repositories.txt)

          if [ ${#TARGET_REPOS[@]} -eq 0 ]; then
            echo "No repositories found for $REPO_NAME"
            exit 0
          fi

          for repo in "${TARGET_REPOS[@]}"; do
            echo "Processing $repo..."
            if ! gh repo view "$repo" >/dev/null 2>&1; then
              echo "Repository $repo not accessible"
              continue
            fi

            for key in $(jq -r 'keys[]' vars.json); do
